version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
#    volumes:
#      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
